services:
  9router:
    image: ghcr.io/storevani/9router:latest
    container_name: 9router
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "20128"
      HOSTNAME: 0.0.0.0
      DATA_DIR: /app/data
    ports:
      - "127.0.0.1:1455:1455"
      - "0.0.0.0:20128:20128"
    volumes:
      - /root/9router/data:/app/data
